// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOrvuBzE5z__rv2GlUImSnxgRogirqD_A',
    appId: '1:982356263031:web:43291b3ba28107741a0672',
    messagingSenderId: '982356263031',
    projectId: 'uotc-20',
    authDomain: 'uotc-20.firebaseapp.com',
    storageBucket: 'uotc-20.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC98tRGRp4EwX1sVO4uYI27uuZaGE0Avnc',
    appId: '1:982356263031:android:4f93f310d549cbd51a0672',
    messagingSenderId: '982356263031',
    projectId: 'uotc-20',
    storageBucket: 'uotc-20.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYOY5TNbZRII0UJOFWlfPYJkoWjNPyn7I',
    appId: '1:982356263031:ios:42771eb8943fa8131a0672',
    messagingSenderId: '982356263031',
    projectId: 'uotc-20',
    storageBucket: 'uotc-20.appspot.com',
    iosClientId: '982356263031-vamkrhfn1hkgj187feog31rv8d95l62m.apps.googleusercontent.com',
    iosBundleId: 'com.example.uotc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYOY5TNbZRII0UJOFWlfPYJkoWjNPyn7I',
    appId: '1:982356263031:ios:42771eb8943fa8131a0672',
    messagingSenderId: '982356263031',
    projectId: 'uotc-20',
    storageBucket: 'uotc-20.appspot.com',
    iosClientId: '982356263031-vamkrhfn1hkgj187feog31rv8d95l62m.apps.googleusercontent.com',
    iosBundleId: 'com.example.uotc',
  );
}
